sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  jwt:
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 720000000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  #阿里云配置
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tATMFst2s9EFNvARHxF
    access-key-secret: KppIciHkLf7XAQBKtoHhau0PL7cMUk
    bucket-name: jscomet-web
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx11ec877a7434f2b5
    secret: 92df9c7a9ac247ca43a737719c500fb3
